# "/" + ä»“åº“çš„åå­—. èµ„æºæ–‡ä»¶çš„è·¯å¾„ç»„æˆéƒ¨åˆ†
baseurl: "/my-first-test"

# ç½‘é¡µçš„æ ‡é¢˜
title: "WHO I AM"
username: é©¬æµ·å°”è¥¿
# ç½‘ç«™å‰¯æ ‡é¢˜
description: "è®°å½•æˆ‘çš„ç”Ÿæ´»ï¼Œå­¦ä¹ å’Œè®­ç»ƒæ„Ÿæ‚Ÿ ğŸ¥³"

aboutme: "æˆ‘çˆ±âš¾"

# å…¶å®ƒé…ç½®, å¯å¿½ç•¥, æ— éœ€ä¿®æ”¹
markdown: kramdown
gems: [jekyll-paginate]
paginate: 3
permalink: /:title/
paginate_path: "/page:num/"
